version: '1'
services:

  cookitup-db:
    image: "postgres"
    container_name: cookitup-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cookitup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=at

  cookitup-app:
    image: "andrejtodorovski5/cookitup"
    container_name: cookitup-app
    environment:
      - DB_SERVER=cookitup-db
      - POSTGRES_DB=cookitup
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=at
    ports:
      - 8080:8080
    links:
      - cookitup-db
      
  cookitup-angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: cookitup-angular
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules


volumes:
  postgres-data:
