name: Docker Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]
jobs:
   docker-build-and-push:
    runs-on: ubuntu-latest
    services:
       postgres:
         image: postgres:15
         env:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: at
           POSTGRES_DB: cookitup
         ports:
           - 5432:5432
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      -
        name: Wait for PostgreSQL to start
        run: sleep 10
      -
        name: Build with Gradle
        run: |
          cd Backend/CookItUp
          chmod +x gradlew
          ./gradlew clean build --info
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Backend/CookItUp/Dockerfile
          tags: andrejtodorovski5/cookitup:latest
